### ISSUE TITLE
A Dashboard with Total Power Consumption and Cost.

### ISSUE THREAD

**Issue by manojkarmacharya-github** [cisco-open/green-monitoring#15]
## Problem Statement

At the moment, power consumption and cost is available for device. From operation point, it's better to have per site power, cost and CO2 emission along with total power, cost and CO2 emission for entire infrastructure

**Comment by cprecup** [comment]
Hi @manojkarmacharya-github - this has been tested and can be addressed by adding a site tag in the mapping configuration file: https://github.com/cisco-open/green-monitoring/blob/main/stack/telegraf/telegraf.d/telegraf-mapping.conf. Consequently, one would tailor the database queries to filter the content based on the site in question and sum up the values.
